extends Node
## Plays cues and music. Assets resolve from assets/audio/<id>.ogg or .wav (first found); missing
## assets are logged once and skipped so content never crashes on a missing cue. Cues with numbered
## variations (<id>_v1.., generated by tools/build_audio.py) are rotated to avoid repetition.
## Every meaningful cue has a textual equivalent (subtitle) when the player enables it.

signal subtitle(text: String)

const EXTENSIONS := [".ogg", ".wav"]
const MAX_VARIATIONS := 4
const MUSIC_FADE := 0.6

var _players: Array[AudioStreamPlayer] = []
var _music: AudioStreamPlayer
var _current_music := ""
var _missing_reported: Dictionary = {}
var _variation_index: Dictionary = {}
var _stream_cache: Dictionary = {}
var _sub_keys := {
	"sfx_telegram": "audio.telegram", "sfx_warning": "audio.warning", "sfx_death": "audio.death",
	"sfx_unlock": "audio.unlock", "sfx_revelation": "audio.revelation", "sfx_success": "audio.success",
	"sfx_res_danger": "audio.warning", "sfx_gate_move": "audio.gate", "sfx_bell": "audio.bell",
	"mus_crisis": "audio.crisis_music", "mus_ending_true": "audio.true_music", "mus_ending_fail": "audio.fail_music",
}


func _ready() -> void:
	for i in range(6):
		var p := AudioStreamPlayer.new()
		add_child(p)
		_players.append(p)
	_music = AudioStreamPlayer.new()
	add_child(_music)
	Settings.changed.connect(_apply_volumes)
	_apply_volumes()


func _apply_volumes() -> void:
	var m := float(Settings.get_value("music_volume"))
	var s := float(Settings.get_value("sfx_volume"))
	_music.volume_db = linear_to_db(max(m, 0.0001))
	for p in _players:
		p.volume_db = linear_to_db(max(s, 0.0001))


## Path of an existing audio asset for `id`, or "" if none.
static func asset_path(id: String) -> String:
	for ext in EXTENSIONS:
		var path := "res://assets/audio/%s%s" % [id, ext]
		if ResourceLoader.exists(path):
			return path
	return ""


func _load(id: String) -> AudioStream:
	if _stream_cache.has(id):
		return _stream_cache[id]
	var path := asset_path(id)
	if path == "":
		if not _missing_reported.has(id):
			_missing_reported[id] = true
			push_warning("[AudioBus] missing audio asset %s" % id)
		return null
	var stream: AudioStream = load(path)
	_stream_cache[id] = stream
	return stream


## Picks <id> or one of its numbered variations, rotating so the same cue rarely repeats twice.
func _variant(id: String) -> String:
	var names := [id]
	for i in range(1, MAX_VARIATIONS):
		if asset_path("%s_v%d" % [id, i]) != "":
			names.append("%s_v%d" % [id, i])
	if names.size() == 1:
		return id
	var idx := (int(_variation_index.get(id, -1)) + 1) % names.size()
	_variation_index[id] = idx
	return names[idx]


func play_sfx(id: String) -> void:
	_emit_subtitle(id)
	if float(Settings.get_value("sfx_volume")) <= 0.0:
		return
	var stream := _load(_variant(id))
	if stream == null:
		return
	for p in _players:
		if not p.playing:
			p.stream = stream
			p.play()
			return
	_players[0].stream = stream
	_players[0].play()


func play_music(id: String) -> void:
	if id == _current_music:
		return
	_current_music = id
	_emit_subtitle(id)
	var stream := _load(id)
	if stream == null:
		_music.stop()
		return
	_set_loop(stream, id.begins_with("mus_") and not id.begins_with("mus_ending"))
	_music.stream = stream
	_music.play()


static func _set_loop(stream: AudioStream, on: bool) -> void:
	if stream is AudioStreamOggVorbis:
		(stream as AudioStreamOggVorbis).loop = on
	elif stream is AudioStreamWAV:
		(stream as AudioStreamWAV).loop_mode = AudioStreamWAV.LOOP_FORWARD if on else AudioStreamWAV.LOOP_DISABLED


func stop_music() -> void:
	_current_music = ""
	_music.stop()


func _emit_subtitle(id: String) -> void:
	if Settings.get_value("subtitles") and _sub_keys.has(id):
		subtitle.emit(Loc.ui(_sub_keys[id].trim_prefix("ui."), ""))
