#!/usr/bin/env python3
"""Generate content/characters/*.json from the canonical character table.

Run once (or after editing the table below); the JSON files are committed.
"""
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[1]
OUT = ROOT / "content" / "characters"

ACCENT = {
    "company": "#3F7D5A", "town": "#9C5A3C", "hullfolk": "#8C6B2F",
    "aldmere": "#3B5F8A", "sorrel": "#B4482B", "concordance": "#7C8FA6", "none": "#7C8FA6",
}

MAJOR = [
    dict(id="vosk", name="Odile Vosk", role="Summit Auditor", faction="company",
         expressions=["neutral", "measuring", "tired", "rare_warmth"],
         silhouette="Tall, narrow, grey travelling coat buttoned to the throat, document case held flat like a tray.",
         speech_rhythm="Short declaratives. Never asks a question she cannot answer. Pauses before names.",
         vocabulary=["irregular", "noted", "the works", "for the record", "you will find"],
         prohibited_phrases=["I think", "sorry", "!", "okay", "please"],
         public_motivation="Keep the summit accounts and the Keeper honest.",
         private_motivation="Keep the Marrow Cut secret; disclosure ends canal, town and peace.",
         fear="That she is the last who knows, and that she is wrong.",
         contradiction="An auditor whose job is concealing the largest fraud on the canal.",
         secret="Has read Marrow's letters; filed Dray as 'resigned'.",
         relationships={"pell": "contempt for his sincerity; protects him from it", "quenn": "fears she will find the survey", "mirren": "guilt", "hale": "unspoken pact"},
         initial_relationship=45),
    dict(id="pell", name="Gideon Pell", role="Superintendent", faction="company",
         expressions=["beaming", "neutral", "wounded", "stern"],
         silhouette="Broad, waistcoat straining, Company-green sash, brass speaking trumpet he does not need.",
         speech_rhythm="Long, rolling, three adjectives where one would do. Announces the player: 'Keeper!'",
         vocabulary=["magnificent", "the Meridian spirit", "throughput", "our little difficulty"],
         prohibited_phrases=["damn", "I doubt", "tired", "we hold"],
         public_motivation="A glorious Jubilee and record traffic.",
         private_motivation="To be remembered; a Board seat.",
         fear="Irrelevance; Sorrel newspapers laughing.",
         contradiction="Loves the canal and town sincerely and causes half its floods.",
         secret="Reviving the Clearance Order draft 'as a contingency'.",
         relationships={"vosk": "thinks she is his subordinate", "ilse": "feud over brewery rent", "hesse": "obsessed with his reviews", "crane": "rival in pomp"},
         initial_relationship=55),
    dict(id="quenn", name="Tamsin Quenn", role="Company Engineer", faction="company",
         expressions=["worried", "absorbed", "neutral", "resolved"],
         silhouette="Small, ink-stained cuffs, oversized folio of drawings, hair escaping a cap.",
         speech_rhythm="Fast, self-interrupting, numbers first, apologizes for facts.",
         vocabulary=["the figures", "sorry", "it doesn't close", "roughly", "the aqueduct"],
         prohibited_phrases=["magnificent", "I swear", "we hold", "Schedule"],
         public_motivation="Keep gates and paddles working with no budget.",
         private_motivation="Make the reservoir sums balance. They never do.",
         fear="Being right.",
         contradiction="The most honest person on the summit keeps her findings in a drawer.",
         secret="Holds a copy of Marrow's Y6 survey she has not dared read fully.",
         relationships={"vosk": "terror", "pell": "exasperated fondness", "tamm": "friendship, shared tools", "mirren": "mentor"},
         initial_relationship=50),
    dict(id="ilse", name="Ilse Harrow", role="Innkeeper and Town Reeve", faction="town",
         expressions=["neutral", "wry", "angry", "grieving"],
         silhouette="Solid, sleeves rolled, apron over a reeve's chain, a tally slate.",
         speech_rhythm="Plain. One clause, then the price. 'Keeper' without warmth until earned, then no title at all.",
         vocabulary=["cellar", "the moot", "what it costs", "your Company"],
         prohibited_phrases=["magnificent", "irregular", "the gift", "blessed"],
         public_motivation="Dry cellars, fair rent, work for the town.",
         private_motivation="Her son drowned after the Y44 riot; the town must never rise and never be pushed again.",
         fear="The town burning its own bridges.",
         contradiction="The moderate who runs the town's only illegal water sale.",
         secret="The brewery well is fed by a crack from the pound; the ale is Company water.",
         relationships={"pell": "rent war", "bram": "old respect, mooring friction", "cole": "rival", "stroud": "friend"},
         initial_relationship=45),
    dict(id="mirren", name="Mirren Dray", role="Lock Hand", faction="town",
         expressions=["guarded", "neutral", "hopeful", "broken"],
         silhouette="Young, wiry, oilskin too large (her father's), a windlass over the shoulder.",
         speech_rhythm="Clipped. Drops the last word when it hurts. Direct questions.",
         vocabulary=["he", "the study", "did you", "the paddles"],
         prohibited_phrases=["father", "magnificent", "irregular", "cargo"],
         public_motivation="Keep her post and her father's house.",
         private_motivation="Find where Ansel Dray went.",
         fear="That he left on purpose.",
         contradiction="Works daily for the Company she suspects killed him.",
         secret="Has his ciphered ledger; has told no one.",
         relationships={"quenn": "apprentice", "vosk": "hostility", "wren": "uneasy friendship", "tobin": "the only one who tells stories of her father"},
         initial_relationship=40),
    dict(id="bram", name="Bram Holloway", role="Holder of the Reed Reach", faction="hullfolk",
         expressions=["neutral", "patient", "stern", "mourning"],
         silhouette="Old, immense, always seated on a bollard or gunwale, stitched-sailcloth coat, unlit pipe.",
         speech_rhythm="Slow, plural ('we hold', 'we remember'), one proverb per meeting, never threat or plea.",
         vocabulary=["holding", "the remembered", "water debt", "the river"],
         prohibited_phrases=["please", "Company", "!", "quick", "hurry"],
         public_motivation="Keep the holdings; be left alone.",
         private_motivation="Recover the Hullfolk's name; have the theft of the river said aloud.",
         fear="That the young forget, or that they burn something.",
         contradiction="A man of peace whose people could sabotage the canal, and who decides yearly not to.",
         secret="Knows where the Cut's outfall is; has never gone in.",
         relationships={"wren": "grandfather in all but blood", "petronel": "oldest friend", "ilse": "respect, mooring feud", "solas": "two old soldiers"},
         initial_relationship=40),
    dict(id="wren", name="Wren Ashby", role="Hullfolk Runner", faction="hullfolk",
         expressions=["grinning", "neutral", "caught", "serious"],
         silhouette="Lean, barefoot on gunwales, patched jacket with too many pockets, a coil of line.",
         speech_rhythm="Quick, deflecting, answers questions with offers; understatement.",
         vocabulary=["cargo", "a favor", "the old man", "you didn't see"],
         prohibited_phrases=["we hold", "we remember", "Keeper, sir", "magnificent"],
         public_motivation="Money and passage.",
         private_motivation="Get the Hullfolk something the town cannot take.",
         fear="Ending like Bram, sitting on a bollard remembering.",
         contradiction="The least sentimental Hullfolk learns the whole Song.",
         secret="Runs rifles for Sorrel through the reeds.",
         relationships={"bram": "love, defiance", "petronel": "grandmother", "solas": "buyer, and the man she fears", "mirren": "one honest friendship"},
         initial_relationship=45),
    dict(id="crane", name="Matthias Crane", role="Aldmere Customs Inspector", faction="aldmere",
         expressions=["neutral", "disapproving", "delighted_by_a_clause", "alarmed"],
         silhouette="Precise, black coat, white stock, spectacles, bound statute book under the arm.",
         speech_rhythm="Complete sentences with citations. Deadpan. Humor entirely accidental.",
         vocabulary=["the Compact", "Schedule Four", "duly", "I note"],
         prohibited_phrases=["roughly", "I feel", "!", "cargo, eh", "magnificent"],
         public_motivation="Enforce the Compact to the letter.",
         private_motivation="Prove Aldmere could run the canal; a six-year report.",
         fear="Disorder. Also being liked.",
         contradiction="The rule-bound official becomes the truth's best witness because he will not lie.",
         secret="Has been counting the water himself; his figures match Quenn's.",
         relationships={"vane": "loathing that is nearly fondness", "solas": "an armed illegality", "pell": "rival pomp", "quenn": "admires her precision"},
         initial_relationship=50),
    dict(id="vane", name="Nessa Vane", role="Sorrel Freight Agent", faction="sorrel",
         expressions=["brisk", "neutral", "amused", "furious"],
         silhouette="Sharp travelling suit, a rate card in one hand and a pocket watch in the other.",
         speech_rhythm="Fast, numbers and deadlines, interrupts, ends with a deal.",
         vocabulary=["delay costs", "my principals", "by the next watch", "we can fix that"],
         prohibited_phrases=["Schedule", "the gift", "magnificent", "we hold"],
         public_motivation="Coal east, iron east, faster.",
         private_motivation="Buy the canal's Sorrel half for a consortium.",
         fear="That the canal is dying and her contracts with it.",
         contradiction="Wants the Company gone and needs the canal to be a lie.",
         secret="Her consortium is financed by the people who buy Wren's rifles.",
         relationships={"crane": "the loathing", "solas": "employer", "hesse": "feeds him stories", "pell": "flatters him"},
         initial_relationship=50),
    dict(id="solas", name="Captain Ferrant Solas", role="Sorrel Escort Company", faction="sorrel",
         expressions=["neutral", "weary", "hard", "almost_smiling"],
         silhouette="Worn grey uniform without insignia, one stiff arm, a sabre never drawn.",
         speech_rhythm="Quiet, economical, soldier's understatement, one dry observation per card.",
         vocabulary=["my people", "the convoy", "orders", "it won't come to that"],
         prohibited_phrases=["!", "magnificent", "Schedule", "glorious"],
         public_motivation="Get convoys through; pay his men.",
         private_motivation="Never fight another war.",
         fear="Being ordered to fire on the town or the Hullfolk.",
         contradiction="An armed man who is the summit's most reliable pacifist.",
         secret="Knows the rifles are for a Sorrel coup faction.",
         relationships={"bram": "mutual regard", "wren": "buys her rifles, hates it", "vane": "paymaster", "crane": "mutual suspicion"},
         initial_relationship=50),
    dict(id="hale", name="Sister Hale Ambrey", role="Chaplain of the Still Water", faction="concordance",
         expressions=["serene", "neutral", "troubled", "unveiled"],
         silhouette="Grey robe with a blue hem, lamp on a chain, hands always busy with cloth or cup.",
         speech_rhythm="Gentle, sideways, blesses rather than answers. Never says 'no'.",
         vocabulary=["the gift", "still", "tend", "we do not ask the water"],
         prohibited_phrases=["irregular", "cargo", "figures", "no.", "magnificent"],
         public_motivation="Bless vessels, keep the Lamp Vigil, feed the poor at the gate.",
         private_motivation="Protect the founding charter; the gift is still a gift.",
         fear="The spring being explained.",
         contradiction="The kindest person on the summit keeps the cruelest secret out of kindness.",
         secret="The undercroft holds Marrow's letters and the founding donation record.",
         relationships={"vosk": "unspoken pact", "bram": "feeds his people", "stroud": "medicine vs prayer, friendly", "cole": "her landlady"},
         initial_relationship=50),
    dict(id="fennick", name="Fennick Orr", role="Telegraph Clerk", faction="town",
         expressions=["eager", "neutral", "sheepish", "frightened"],
         silhouette="Gangly, eyeshade, ink on his nose, a fan of telegram slips.",
         speech_rhythm="Breathless, parenthetical, tells you the thing he should not first.",
         vocabulary=["you'll never guess", "in strictest confidence", "the wire", "I shouldn't"],
         prohibited_phrases=["we hold", "Schedule", "noted.", "magnificent"],
         public_motivation="Run the wire and be liked.",
         private_motivation="Be important to someone; sells copies of telegrams.",
         fear="Vosk.",
         contradiction="The town's biggest leak keeps the Keeper's secrets when it counts.",
         secret="Transmitted Dray's last wire and kept a copy.",
         relationships={"hesse": "customer", "vane": "customer", "vosk": "terror", "mirren": "hopeless, never stated"},
         initial_relationship=55),
]

SUPPORTING = [
    dict(id="tamm", name="Jory Tamm", role="Boatwright", faction="town", expressions=["neutral", "doubtful"],
         silhouette="Sawdust, leather apron, caulking iron.", speech_rhythm="Terse tradesman's estimates. 'It'll hold or it won't.'",
         vocabulary=["hold", "seams", "a week's work"], prohibited_phrases=["magnificent", "irregular"],
         notes="Repairs; hull evidence; Quenn's friend."),
    dict(id="stroud", name="Dr. Aurelie Stroud", role="Town Physician", faction="town", expressions=["neutral", "grave"],
         silhouette="Black bag, spectacles on a cord, sensible boots.", speech_rhythm="Clinical, kind, blunt about death.",
         vocabulary=["fever", "rest", "I have seen"], prohibited_phrases=["the gift", "magnificent"],
         notes="Fever, drowning, refugees; Fatigue counter."),
    dict(id="dace", name="Corporal Dace", role="Foreman of Lock Hands", faction="town", expressions=["neutral", "fed_up"],
         silhouette="Ex-soldier, whistle, sleeves torn at the seam.", speech_rhythm="Bluff, reports in lists. 'Three things, Keeper.'",
         vocabulary=["three things", "the hands", "paddles"], prohibited_phrases=["magnificent", "the gift"],
         notes="Labor, strikes, requisition."),
    dict(id="cole", name="Marguerite Cole", role="Landlady and Moneylender", faction="town", expressions=["pleasant", "cold"],
         silhouette="Widow's black, keys at the waist, a ledger of her own.", speech_rhythm="Sweet, exact; every sentence carries interest.",
         vocabulary=["terms", "kindly", "due"], prohibited_phrases=["we hold", "magnificent"],
         notes="Loans; owns the chapel and half the town."),
    dict(id="petronel", name="Petronel Ashby", role="Hullfolk Singer", faction="hullfolk", expressions=["neutral", "singing"],
         silhouette="Tiny, shawled, a one-string fiddle.", speech_rhythm="Song fragments and short memories.",
         vocabulary=["the river", "we sang", "into the hill"], prohibited_phrases=["irregular", "magnificent", "cargo"],
         notes="Keeper of the Lowmere Song."),
    dict(id="hesse", name="Lucan Hesse", role="Editor, Sorrel Courier", faction="sorrel", expressions=["curious", "triumphant"],
         silhouette="Notebook, loud checked coat, cigar unlit.", speech_rhythm="Headlines; questions as accusations.",
         vocabulary=["my readers", "on the record", "front page"], prohibited_phrases=["we hold", "the gift"],
         notes="Public opinion; expose or protect."),
    dict(id="tobin", name="Old Tobin", role="Retired Keeper of Lock 8", faction="town", expressions=["neutral", "remembering"],
         silhouette="Bent, forty-year-old Company coat, a tankard.", speech_rhythm="Rambling stories with a true fact buried.",
         vocabulary=["in my day", "Dray", "the Dry Year"], prohibited_phrases=["magnificent", "Schedule"],
         notes="Oral history; Dray's friend; Dry Year witness."),
    dict(id="kell", name="Ambrose Kell", role="Board Commissioner", faction="company", expressions=["courteous", "final"],
         silhouette="Immaculate, silver-topped cane, never sits.", speech_rhythm="Courteous menace; 'the Board's view'.",
         vocabulary=["the Board", "regrettably", "arrangements"], prohibited_phrases=["we hold", "sorry"],
         notes="Arrives in crises and endings; the Company embodied."),
]

SOURCES = [
    dict(id="src_gate", name="At the Gate", role="A vessel at the lock", faction="none", expressions=["neutral"]),
    dict(id="src_telegram", name="Telegram", role="A slip from the wire", faction="none", expressions=["neutral"]),
    dict(id="src_weather", name="The Pound", role="Weather and water", faction="none", expressions=["neutral"]),
    dict(id="src_ledger", name="The Keeper's Ledger", role="Your own record", faction="none", expressions=["neutral"]),
    dict(id="src_stranger", name="A Stranger", role="An unnamed petitioner", faction="none", expressions=["neutral"]),
]


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    for tier, rows in (("major", MAJOR), ("supporting", SUPPORTING), ("source", SOURCES)):
        for row in rows:
            data = {"id": row["id"], "name": row["name"], "role": row["role"], "tier": tier,
                    "faction": row["faction"], "expressions": row["expressions"],
                    "portrait_prefix": row["id"], "accent_color": ACCENT[row["faction"]]}
            for key in ("silhouette", "speech_rhythm", "vocabulary", "prohibited_phrases", "public_motivation",
                        "private_motivation", "fear", "contradiction", "secret", "relationships",
                        "initial_relationship", "notes"):
                if key in row:
                    data[key] = row[key]
            if tier != "source":
                data.setdefault("initial_relationship", 50)
            (OUT / f"{row['id']}.json").write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n")
    print(f"wrote {len(MAJOR) + len(SUPPORTING) + len(SOURCES)} character files to {OUT}")


if __name__ == "__main__":
    main()
